from typing import Protocol, Optional
from app.models.entry import ResultUpdate


class EntryStore(Protocol):
    def list_all(self) -> list[dict]: ...
    def get(self, entry_id: str) -> Optional[dict]: ...
    def create(self, item: dict) -> dict: ...
    def update(self, entry_id: str, body: ResultUpdate) -> dict: ...
    def delete(self, entry_id: str) -> None: ...
