services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
